// src/models/handover.model.ts
import {
  Table,
  Column,
  Model,
  DataType,
  PrimaryKey,
  Default,
  AllowNull,
  ForeignKey,
  BelongsTo,
  CreatedAt,
  Index,
} from "sequelize-typescript";
import { Project } from "./project.model";
import { Attachment } from "./attachment.model";

@Table({
  tableName: "handovers",
  timestamps: true,
  createdAt: "autogenerated_at",
  updatedAt: false, // no updated_at in original schema
  indexes: [
    {
      fields: ["project_id"],
      unique: true, // enforces 1:1 relationship with project
      name: "uk_handovers_project_id",
    },
  ],
})
export class Handover extends Model {
  @PrimaryKey
  @Default(DataType.UUIDV4)
  @Column({
    type: DataType.UUID,
    allowNull: false,
  })
  declare id: string;

  @AllowNull(false)
  @ForeignKey(() => Project)
  @Column(DataType.UUID)
  declare project_id: string;

  @BelongsTo(() => Project, {
    foreignKey: "project_id",
    onDelete: "CASCADE",
  })
  declare project?: Project;

  @Column(DataType.DATEONLY)
  declare handover_date: Date | null;

  @Column(DataType.JSON)
  declare planned_vs_actual_timeline: any | null; // MySQL JSON column

  @Column(DataType.TEXT)
  declare scope_summary: string | null;

  @Default(false)
  @Column(DataType.BOOLEAN)
  declare completion_confirmation: boolean;

  @Column(DataType.TEXT)
  declare outstanding_items: string | null;

  @Default(12)
  @Column(DataType.INTEGER)
  declare warranty_months: number;

  @Column(DataType.TEXT)
  declare maintenance_notes: string | null;

  @Column(DataType.DATE) // TIMESTAMPTZ → DATE (store in UTC)
  declare client_signed_at: Date | null;

  @Column(DataType.DATE)
  declare firm_signed_at: Date | null;

  // References to attachments (PDF summary & drawings archive)
  @ForeignKey(() => Attachment)
  @Column(DataType.UUID)
  declare handover_pdf_id: string | null;

  @BelongsTo(() => Attachment, {
    foreignKey: "handover_pdf_id",
    as: "handoverPdf",
    constraints: false, // soft reference – attachment can be deleted independently
  })
  declare handoverPdf?: Attachment;

  @ForeignKey(() => Attachment)
  @Column(DataType.UUID)
  declare drawings_zip_id: string | null;

  @BelongsTo(() => Attachment, {
    foreignKey: "drawings_zip_id",
    as: "drawingsZip",
    constraints: false,
  })
  declare drawingsZip?: Attachment;

  @CreatedAt
  @Default(DataType.NOW)
  declare autogenerated_at: Date;
}
