import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsUUID,
  IsString,
  IsEnum,
  IsBoolean,
  IsOptional,
  IsArray,
  IsNotEmpty,
} from 'class-validator';
export enum PitchStatus {
  DRAFT = 'Draft',
  PENDING_REVIEW = 'Pending Review',
  APPROVED = 'Approved',
  REJECTED = 'Rejected',
}
export class CreateProjectPitchDto {
  @ApiPropertyOptional({ example: 'Modern Minimalist' })
  @IsOptional()
  @IsString()
  preferred_design_style?: string;

  @ApiPropertyOptional({ enum: ['Light', 'Dark', 'Mixed', 'Not Sure'] })
  @IsOptional()
  @IsEnum(['Light', 'Dark', 'Mixed', 'Not Sure'])
  color_tone?: 'Light' | 'Dark' | 'Mixed' | 'Not Sure';

  @ApiPropertyOptional({ enum: ['Low', 'Medium', 'High'] })
  @IsOptional()
  @IsEnum(['Low', 'Medium', 'High'])
  luxury_level?: 'Low' | 'Medium' | 'High';

  @ApiPropertyOptional({
    example: 'More focus on functionality than aesthetics',
  })
  @IsOptional()
  @IsString()
  functional_vs_aesthetic?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  budget_flexibility?: boolean;

  @ApiPropertyOptional({
    description: 'Array of priority areas like ["Kitchen", "Living Room"]',
  })
  @IsOptional()
  @IsArray()
  priority_areas?: string[];

  @ApiPropertyOptional({
    example: 'I love natural light and wooden textures...',
  })
  @IsOptional()
  @IsString()
  likes_dislikes?: string;

  @ApiPropertyOptional({ example: 'No red color, No open kitchen' })
  @IsOptional()
  @IsString()
  non_negotiables?: string;

  @ApiPropertyOptional({ example: 'Must have smart home integration' })
  @IsOptional()
  @IsString()
  special_requirements?: string;

  @ApiPropertyOptional({ enum: PitchStatus })
  @IsOptional()
  @IsEnum(PitchStatus)
  status?: PitchStatus;
  // These two should NOT be sent from frontend anymore
  @ApiPropertyOptional({
    description: 'Auto-generated by backend after file upload',
  })
  @IsOptional()
  @IsString()
  pitch_pdf_url?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  moodboard_pdf_url?: string;
}
