import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  CreateDateColumn,
} from 'typeorm';
import { Project } from '@/projects/entities/project.entity';
import { Attachment } from '@/attachments/entities/attachments.entity';

@Entity('handovers')
export class Handover {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column('uuid')
  project_id!: string;

  @ManyToOne(() => Project, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'project_id' })
  project!: Project;

  @Column({ type: 'date', nullable: true })
  handover_date?: Date;

  @Column({ type: 'jsonb', nullable: true })
  planned_vs_actual_timeline?: Record<string, any>;

  @Column('text', { nullable: true })
  scope_summary?: string;

  @Column({ default: false })
  completion_confirmation!: boolean;

  @Column('text', { nullable: true })
  outstanding_items?: string;

  @Column({ default: 12 })
  warranty_months!: number;

  @Column('text', { nullable: true })
  maintenance_notes?: string;

  @Column({ type: 'timestamptz', nullable: true })
  client_signed_at?: Date;

  @Column({ type: 'timestamptz', nullable: true })
  firm_signed_at?: Date;

  @Column('uuid', { nullable: true })
  handover_pdf_id?: string;

  @ManyToOne(() => Attachment, { nullable: true })
  @JoinColumn({ name: 'handover_pdf_id' })
  handoverPdf?: Attachment;

  @Column('uuid', { nullable: true })
  drawings_zip_id?: string;

  @ManyToOne(() => Attachment, { nullable: true })
  @JoinColumn({ name: 'drawings_zip_id' })
  drawingsZip?: Attachment;

  @CreateDateColumn()
  autogenerated_at!: Date;
}
